import os
import re
from pathlib import Path

SOURCES = ['Sources']
TESTS_DIR = Path('Tests/Generated')
TESTS_DIR.mkdir(parents=True, exist_ok=True)

for src_root in SOURCES:
    for path in Path(src_root).rglob('*.swift'):
        text = path.read_text()
        matches = re.findall(r'class\s+(\w+):', text)
        for cls in matches:
            test_file = TESTS_DIR / f'{cls}Tests.swift'
            if test_file.exists():
                continue
            test_file.write_text(f"import XCTest\n@testable import CreatorCoreForge\n\nfinal class {cls}Tests: XCTestCase {{\n    func testExample() throws {{\n        // TODO: autogenerated stub\n    }}\n}}\n")
