name: Auto-Coder

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  codex-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Auto Code Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/auto_code_bot.py --upgrade-placeholders --complete-todos --complete-stubs
      - name: Push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git push

