name: Upload Apps to App Store Connect

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    strategy:
      matrix:
        app:
          - name: CoreForge Audio
            path: apps/CoreForgeAudio/VocalVerseFull
            scheme: VocalVerse
          - name: CoreForge Visual
            path: apps/CoreForgeVisual/LoreForgeAIFull
            scheme: LoreForgeAI
          - name: CoreForge Writer
            path: apps/CoreForgeWriter/InkwellAIFull
            scheme: InkwellAI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build and Deliver ${{ matrix.app.name }}
        env:
          PROJECT_PATH: ${{ matrix.app.path }}/${{ matrix.app.scheme }}.xcodeproj
          SCHEME: ${{ matrix.app.scheme }}
          APPSTORECONNECT_KEY_ID: ${{ secrets.APPSTORECONNECT_KEY_ID }}
          APPSTORECONNECT_ISSUER_ID: ${{ secrets.APPSTORECONNECT_ISSUER_ID }}
          APPSTORECONNECT_API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
          APPSTORECONNECT_TEAM_ID: ${{ secrets.APPSTORECONNECT_TEAM_ID }}
        run: fastlane build_and_deliver
