name: Upload Apps to TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest

=======
    strategy:
      matrix:
        app:
          - name: CoreForge Audio
            path: apps/CoreForgeAudio
            scheme: CoreForgeAudio
          - name: CoreForge Visual
            path: apps/CoreForgeVisual
            scheme: CoreForgeVisual
          - name: CoreForge Writer
            path: apps/CoreForgeWriter
            scheme: CoreForgeWriter


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build and Upload All Apps
        env:
          APPSTORECONNECT_KEY_ID: ${{ secrets.APPSTORECONNECT_KEY_ID }}
          APPSTORECONNECT_ISSUER_ID: ${{ secrets.APPSTORECONNECT_ISSUER_ID }}
          APPSTORECONNECT_API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
          APPSTORECONNECT_TEAM_ID: ${{ secrets.APPSTORECONNECT_TEAM_ID }}
        run: fastlane build_all

      - name: Upload All IPAs to Google Drive
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          find build -name '*.ipa' -print0 | while IFS= read -r -d '' ipa; do
            ./scripts/upload_to_drive.sh "$ipa" "$GDRIVE_FOLDER_ID"
          done
